- hosts: localhost
  become: true
  vars:
    ansible_user: alecwang
    node_version: v18.16.1
    python_version: 3.10.12
    source_dir: "/home/alecwang/DevMachineSetup"
    git_username: alswang18
    git_email: alec.sy.wang@gmail.com
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
  tasks:
    - name: Install zsh
      apt:
        name: zsh
        state: present

    - name: Set Zsh as default shell
      ansible.builtin.command:
        cmd: chsh -s /usr/bin/zsh "{{ ansible_user }}"
      become: true
      become_user: root
    # sets up github
    - import_tasks: ./tasks/git.yml
    # sets up ssh
    - import_tasks: ./tasks/ssh.yml
    # installs oh-my-zsh
    - import_tasks: ./tasks/install_oh_my_zsh.yml
    # # installs node js stuff
    - import_tasks: ./tasks/install_fnm.yml
    # # installs rust stuff
    - import_tasks: ./tasks/install_cargo_and_crates.yml
    # # installs python stuff
    - import_tasks: ./tasks/install_pyenv.yml