- name: Clone oh-my-zsh repository
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ ansible_user }}/.oh-my-zsh
    depth: 1
    force: yes

- name: Install zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /home/{{ ansible_user }}/.oh-my-zsh/plugins/zsh-autosuggestions
    depth: 1

- name: Install fzf plugin
  git:
    repo: https://github.com/unixorn/fzf-zsh-plugin.git
    dest: /home/{{ ansible_user }}/.oh-my-zsh/plugins/fzf-zsh-plugin

- name: Create .zshrc file
  copy:
    content: |
      export ZSH="/home/{{ ansible_user }}/.oh-my-zsh"
      ZSH_THEME="bureau"
      plugins=(z git zsh-autosuggestions fzf-zsh-plugin)
      source $ZSH/oh-my-zsh.sh
    dest: /home/{{ ansible_user }}/.zshrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
