- name: Wait for .zshrc file to be generated (pyenv)
  wait_for:
    path: /home/alecwang/.zshrc
    state: present

- name: Install pyenv dependencies
  apt:
    name:
      - libssl-dev 
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev 
      - libsqlite3-dev
      - libncursesw5-dev 
      - xz-utils 
      - tk-dev 
      - libxml2-dev 
      - libxmlsec1-dev 
      - libffi-dev 
      - liblzma-dev
      - libpq-dev
    state: present
  become: true

- name: Curl install pyenv
  shell: |
    curl https://pyenv.run | bash
    export PYENV_ROOT="$HOME/.pyenv"
    command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    pyenv install "{{ python_version }}"
    pyenv global "{{ python_version }}"
  become: true
  become_user: alecwang
  become_method: sudo
  environment:
    HOME: /home/alecwang

- name: Add pyenv configuration to .zshrc
  lineinfile:
    path: /home/alecwang/.zshrc
    line: |
      # pyenv configuration
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
  become: true
  become_user: alecwang
  become_method: sudo
  environment:
    HOME: /home/alecwang